language: node_js
node_js:
  - "8"

cache:
  bundler: true
  directories:
    - node_modules # NPM packages

install:
  - npm i -g jest npm
  - npm i

script:
  - jest --coverage

after_success:
  - codecov
